Update to binutils-2.28.

diff --git a/Main/binutils/PKGBUILD b/Main/binutils/PKGBUILD
--- a/Main/binutils/PKGBUILD
+++ b/Main/binutils/PKGBUILD
@@ -1,7 +1,7 @@
 # Maintainer: DJ Lucas <dj_AT_linuxfromscratch_DOT_org>
 
 pkgname=binutils
-pkgver=2.27
+pkgver=2.28
 pkgrel=1
 pkgdesc="The Binutils package contains a linker, an assembler, and other tools for handling object files."
 arch=('i686' 'x86_64')
@@ -32,10 +32,10 @@ prepare(){
 build(){ 
   cd ${srcdir}/${pkgname}-${pkgver}/build
   ../configure --prefix=/usr       \
-               --enable-shared     \
+               --enable-gold       \
                --enable-ld=default \
                --enable-plugins    \
-               --enable-gold       \
+               --enable-shared     \
                --disable-werror    \
                --with-system-zlib
   # Make sure build environment is sane before wasting time
@@ -46,11 +46,15 @@ build(){
 
 check(){
   cd ${srcdir}/${pkgname}-${pkgver}/build
-  make LDFLAGS="" check
+  make LDFLAGS="" -k check 2>&1 | tee test.log || true
+  failures=`grep "failed" test.log | wc -l`
+  if test "${failures}" != "1"; then
+    echo "Unexpected test failure..." && exit 1
+  fi
 }
 
 package(){
   cd ${srcdir}/${pkgname}-${pkgver}/build
   make prefix=${pkgdir}/usr tooldir=${pkgdir}/usr install
 }
-sha256sums=('369737ce51587f92466041a97ab7d2358c6d9e1b6490b3940eb09fb0a9a6ac88')
+sha256sums=('6297433ee120b11b4b0a1c8f3512d7d73501753142ab9e2daa13c5a3edd32a72')
